name: date_time_picker
description: A Flutter widget to display a date time form field to show a date or clock dialog.
version: 2.1.0
homepage: https://github.com/m3uzz/date_time_picker

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
